# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_price', models.BigIntegerField()),
                ('good_description', models.TextField(max_length=400, null=True)),
                ('good_title', models.CharField(max_length=200, null=True)),
                ('good_image', models.ImageField(blank=True, null=True, upload_to='goodimages/')),
                ('good_number', models.PositiveSmallIntegerField(null=True)),
                ('good_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedgood_date', models.DateTimeField(null=True)),
                ('orderedgood_number', models.PositiveSmallIntegerField(null=True)),
                ('orderedgood_total_price', models.BigIntegerField(null=True)),
                ('orderedgood_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedgood_description', models.TextField(max_length=400, null=True)),
                ('requestedgood_title', models.CharField(max_length=200, null=True)),
                ('requestedgood_image', models.ImageField(blank=True, null=True, upload_to='reqgoodimages/')),
                ('requestedgood_number', models.PositiveSmallIntegerField(null=True)),
                ('requestedgood_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='good_requestedgood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RequestedGood'),
        ),
    ]
