# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_data',
            field=models.DateTimeField(null=True),
        ),
    ]
