# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171107_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedgood',
            name='requestgood_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
