# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_good_good_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='good_requester',
        ),
    ]
