# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171108_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_is_final',
            field=models.BooleanField(default=False),
        ),
    ]
