# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='myprofile_company_address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='myprofile_company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='myprofile_company_phonenumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='myprofile_fullname',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='myprofile_is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
